
services:
  backend:
    build: ./backend
    container_name: recycnet-backend
    volumes:
      - /home/tarun/app/models:/app/models:ro
    environment:
      - MODEL_PATH=/app/models/recycnetAI-10
    networks:
      - recycnet-network
    
  frontend:
    build: ./recycnet-ai
    container_name: recycnet-frontend
    ports:
      - "8003:80"
    environment:
      - REACT_APP_API=https://recycnetai.tarunteja.dev/classify
    networks:
      - recycnet-network
  
networks:
  recycnet-network:
    driver: bridge