
services:
  backend:
    build: ./backend
    container_name: recycnet-backend
    restart: always
    volumes:
      - ./models:/app/models:ro
    environment:
      - MODEL_PATH=/app/models/recycnetAI-10
    networks:
      - recycnet-network
    
  frontend:
    build: ./recycnet-ai
    container_name: recycnet-frontend
    restart: always
    environment:
      - REACT_APP_API=http://recycnet-backend:8000/classify
    networks:
      - recycnet-network
  
networks:
  recycnet-network:
    driver: bridge